pluginservice/apps/api/urls.py
from django.conf.urls import patterns, url
from .views import API, Styles, InviteViewSet, UserViewSet, UserDetailViewSet


urlpatterns = patterns(
    '',
    url(r'^api/polls/(?P<pk>\d+).js$', API.as_view(), name='Api'),
    url(r'^api/polls/styles.css$', Styles.as_view(), name='Styles'),
    url('^api/users/(?P<team>.+)/$', UserViewSet.as_view()),
    url('^api/invites/$', InviteViewSet.as_view()),
    url('^api/user/(?P<pk>.+)/$', UserDetailViewSet.as_view()),
)

pluginservice/apps/polls/urls.py
from django.conf.urls import patterns, url
from .views import PollCreate, PollCreateSuccess, PollDetail, PollHome


urlpatterns = patterns(
    '',
    #url(r'^$', PollHome.as_view(), name='PollHome'),
    url(r'^create/$', PollCreate.as_view(), name='PollCreate'),
    url(r'^(?P<pk>\d+)/$', PollDetail.as_view(), name='PollDetail'),
    url(r'^(?P<pk>\d+)/help/$', PollCreateSuccess.as_view(), name='success'),
)

pluginservice/apps/teams/urls.py
from django.conf.urls import patterns, url
from .views import TeamList, TeamDetail,TeamCreate, InviteResponse, InviteUser

urlpatterns = patterns(
    '',
    url(r'^$', TeamList.as_view(), name='home'),
    url(r'^(?P<pk>\d+)/$', TeamDetail.as_view(), name='TeamDetail'),
    url(r'^create/$', TeamCreate.as_view(), name='Create'),
    url(r'^invitereponse/$', InviteResponse.as_view(), name='Create'),
    url(r'^invite/$', InviteUser.as_view(), name='Create'),
    
    
    
)

pluginservice/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from django.conf import settings
from .views import Homepage, TempProfile, Widgets, PollJS
from pluginservice.apps.navigation.views import PageDetail
from apps.api.views import InviteViewSet, UserViewSet, NotificationViewSet, PollVoteViewSet, TeamViewSet
from rest_framework import routers

router = routers.DefaultRouter()
router.register(r'users', UserViewSet, base_name='users')
router.register(r'invites', InviteViewSet, base_name='invites')
router.register(r'notifications', NotificationViewSet, base_name='notifications')
router.register(r'votes', PollVoteViewSet, base_name='votes')
router.register(r'teams', TeamViewSet, base_name='teams')

admin.autodiscover()


urlpatterns = patterns(
    '',
    url(r'^$', Homepage.as_view(), name='homepage'),
    url(r'^profile/$', TempProfile.as_view(), name='TempProfile'),
    #url(r'^widgets/$', Widgets.as_view(), name='Widgets'),
    url(r'^widgets/polls/', include('pluginservice.apps.polls.urls', namespace="polls")),
    url(r'^team/', include('pluginservice.apps.teams.urls', namespace="teams")),
    url(r'^', include('pluginservice.apps.accounts.urls', namespace="accounts")),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^login/$', 'django.contrib.auth.views.login', name='login'),
    url(r'^logout/$', 'django.contrib.auth.views.logout', {'next_page': '/'}, name='logout'),
    url(r'^api/', include(router.urls)),
    url(r'^api/widgets/polls/(?P<pk>\d+).js$', PollJS.as_view(), name='PollList'),
    url(r"^(?P<page_slug>[^/]+)/$", PageDetail.as_view(), name="page_slugs"),
)

if settings.DEBUG:
    # static files (images, css, javascript, etc.)
    urlpatterns += patterns('',
        (r'^media/(?P<path>.*)$', 'django.views.static.serve', {
        'document_root': settings.MEDIA_ROOT}))

pluginservice/apps/polls/models.py
from django.db import models
from django.contrib.auth.models import User
from pluginservice.apps.teams.models import Team

class Poll(models.Model):

    title = models.CharField(
        max_length=200,
        )

    question = models.CharField(
        max_length=200,
        )

    image = models.CharField(
        max_length=400,
        blank=True,
        null=True,
        )

    created_by = models.ForeignKey(
        User
        )

    team = models.ForeignKey(
        Team,
        null=True,
        )

    deleted = models.BooleanField(
        default=False,
        )

    def __unicode__(self):
        return self.title


class PollAnswer(models.Model):

    poll = models.ForeignKey(
        Poll,
        )

    answer = models.CharField(
        max_length=200,
        )


    def __unicode__(self):
        return self.answer


class Vote(models.Model):

    choice = models.ForeignKey(
        PollAnswer,
        )

    timestamp = models.DateTimeField(
        auto_now_add=True,
        )

    ip = models.IPAddressField(
        max_length=200,
        null=True,
        )

    def __unicode__(self):
        return self.poll

pluginservice/apps/accounts/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm

class UserCreateForm(UserCreationForm):
    email = forms.EmailField(required=True)

    class Meta:
        model = User
        fields = ("username", "email", "first_name", "last_name", "password1", "password2")

    def save(self, commit=True):
        user = super(UserCreateForm, self).save(commit=False)
        user.email = self.cleaned_data["email"]
        user.first_name = self.cleaned_data["first_name"]
        user.last_name = self.cleaned_data["last_name"]
        if commit:
            user.save()
        return user

pluginservice/apps/accounts/views.py
from django.views.generic import FormView, UpdateView
from django.forms.models import inlineformset_factory
from django.core.urlresolvers import reverse
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm, PasswordChangeForm
from .forms import UserCreateForm
from .models import UserProfile
from django.contrib.auth import authenticate, login

class CreateAccount(FormView):
    template_name = 'accounts/register.html'
    form_class = UserCreateForm
    success_url = '/'

    def form_valid(self, form):
        createform = form.save(commit=False)
        createform.username = form.cleaned_data['username'].lower()
        self.object = form.save()

        user = authenticate(
            username=form.cleaned_data['username'].lower(),
            password=form.cleaned_data['password1']
        )

        if user is not None:
            if user.is_active:
                login(self.request, user)

        return super(CreateAccount, self).form_valid(form)

class ChangePassword(FormView):
    form_class = PasswordChangeForm


class TutorialForm(FormView):
    template_name = 'accounts/register.html'
    success_url = '/'

    def form_valid(self, form):   
        user = UserProfile.get(user=self.request.user)
        user.tutorial_completed = True;
        user.save()


class UserProfileUpdate(FormView):
    model = UserProfile

pluginservice/apps/api/views.py
from django.views.generic import DetailView, TemplateView
from pluginservice.apps.polls.models import Poll, Vote, PollAnswer
from pluginservice.apps.teams.models import Invite, TeamMate, Team
from pluginservice.apps.notifications.models import Notification
from rest_framework import viewsets
#from django.http import HttpRequest
from .serializers import InviteSerializer, UserSerializer, NotificationSerializer, PollVoteSerializer, TeamModelSerializer
from rest_framework import serializers
from django.contrib.auth.models import User
from rest_framework import generics, filters
from datetime import datetime

def TeamPlayers(teamID):
    tlist = []

    players = TeamMate.objects.filter(team=teamID)
    invites = Invite.objects.filter(team=teamID, closed=False)

    for player in invites:
        tlist.append(player.invite_to.id)

    for player in players:
        tlist.append(player.user.id)

    return tlist


def YourTeams(userID):
    tlist = []

    results = TeamMate.objects.filter(user=userID)

    for result in results:
        tlist.append(Team.objects.get(id=result.team.id))

    return tlist


class UserViewSet(viewsets.ReadOnlyModelViewSet):
    """
    View the detail of a user and filter by team the avalible users that can be invited
    """
    def get_queryset(self):
        inviteable = self.request.query_params.get('inviteable', None)
        team = self.request.query_params.get('team', None)
        queryset = User.objects.all();

        if inviteable:
            tlist = TeamPlayers(inviteable)
            return User.objects.exclude(pk__in=tlist)

        if team:
            tlist = TeamPlayers(team)
            return User.objects.filter(pk__in=tlist)


        return queryset

    serializer_class = UserSerializer
    serializer = UserSerializer
    filter_backends = (filters.SearchFilter,)
    search_fields = ('username', 'email')


class InviteViewSet(viewsets.ReadOnlyModelViewSet):
    """
    Returns a list of the current invites you have.
    """
    serializer_class = InviteSerializer

    def get_queryset(self):

        user = self.request.user
        print user
        return Invite.objects.filter(invite_to=user, closed=False)


class NotificationViewSet(viewsets.ReadOnlyModelViewSet):
    """
    Returns a list of the current Notifications you have.
    """
    serializer_class = NotificationSerializer

    def get_queryset(self):
        user = self.request.user
        result = Notification.objects.filter(user=user, read=False)
        print result
        return result


class PollVoteViewSet(viewsets.ModelViewSet):
    """
    Allows someone to vote on a poll
    """

    serializer_class = PollVoteSerializer
    def get_queryset(self):

        """
        step 1 get all the teams the user is in
        step 2 filter by the polls the users is involved in
        step 3 get all the votes ass
        """

        userteammates = TeamMate.objects.filter(user=self.request.user)
        teams = []
        for teammateobject in userteammates:
            teams.append(teammateobject.team)


        #return Vote.objects.filter(team__in=teams)
        return Vote.objects.filter(choice__poll=1)


class TeamViewSet(viewsets.ReadOnlyModelViewSet):
    """
    Returns a list of the current Teams you have.
    """
    serializer_class = TeamModelSerializer

    def get_queryset(self):
        user = self.request.user

        return YourTeams(user)

pluginservice/apps/navigation/views.py
from django.views.generic import DetailView
from .models import Page

class PageDetail(DetailView):
    model = Page
    template_name = 'site/navigation-page.html'
    slug_field = 'slug'
    slug_url_kwarg = 'page_slug'

pluginservice/apps/notifications/views.py
from django.views.generic import FormView
from django.forms.models import inlineformset_factory
from django.core.urlresolvers import reverse
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm, PasswordChangeForm
from .forms import UserCreateForm
from django.contrib.auth import authenticate, login

def CreateNotifcation(to_user, text ):
    return text

pluginservice/apps/polls/views.py
from django.views.generic import ListView, CreateView, DetailView, TemplateView
from .models import Poll, PollAnswer
from django.forms.models import inlineformset_factory
from django.core.urlresolvers import reverse
from pluginservice.settings.production import CURRENT_SITE_URL
from .forms import CreateForm
from pluginservice.apps.teams.models import Team, TeamMate
from django.http import Http404

class PollHome(TemplateView):
    template_name = 'polls/polls_home.html'


def isUserAdmin(self):

    try:
     user = TeamMate.objects.get(team=self.kwargs['pk'], user=self.request.user)

     if user.admin:
        return True
     else:
        return False
    except:
        return False

class PollDetail(DetailView):
    model = Poll

    def get_context_data(self, **kwargs):
        context = super(PollDetail, self).get_context_data(**kwargs)
        poll = Poll.objects.get(id=self.kwargs['pk'])
        context['checker'] = owner(self, poll.team.id)
        return context

def owner(self, teamid):
        people = TeamMate.objects.filter(team=teamid)
        exists = False

        if people:
            for person in people:
                if person.user.id == self.request.user.id:
                    return True
                else:
                    exists = False

            if not exists:
                return False
        else:
            return False    

class PollCreate(CreateView):
    model = Poll
    form_class = CreateForm
    #success_url = '/polls/create/success/'

    def form_valid(self, form):
        PollForm = form.save(commit=False)
        PollForm.created_by = self.request.user
        self.object = form.save()

        choice1 = form.cleaned_data['choice1']
        choice2 = form.cleaned_data['choice2']
        choice3 = form.cleaned_data['choice3']


        if choice1 != "":
            CreateAnswers = PollAnswer.objects.create(poll=self.object, answer=choice1)
            CreateAnswers.save()

        if choice2 != "":
            CreateAnswers = PollAnswer.objects.create(poll=self.object, answer=choice2)
            CreateAnswers.save()

        if choice3 != "":
            CreateAnswers = PollAnswer.objects.create(poll=self.object, answer=choice3)
            CreateAnswers.save()


        return super(PollCreate, self).form_valid(form)

    def get_success_url(self, **kwargs):
        return reverse('polls:success', kwargs={'pk': self.object.id})


class PollCreateSuccess(DetailView):
    model = Poll
    template_name = 'polls/poll_success.html'

    def get_context_data(self, **kwargs):
        context = super(PollCreateSuccess, self).get_context_data(**kwargs)
        context['current_site_url'] = CURRENT_SITE_URL
        return context

pluginservice/apps/teams/views.py
from django.views.generic import TemplateView, CreateView, ListView, FormView, DetailView
from django.contrib.auth.models import User
from .models import Team, Invite, TeamMate
from django.core.urlresolvers import reverse
from .forms import InviteResponseForm, InviteUserForm
from pluginservice.apps.polls.views import owner, isUserAdmin
from pluginservice.apps.polls.models import Poll

class TeamList(ListView):
    model = Team

    def get_queryset(self):
        teamlist = []

        for team in Team.objects.all():
            if owner(self, team.id):
                teamlist.append(team.id)

        queryset = Team.objects.filter(id__in=teamlist)
        return queryset



class TeamDetail(DetailView):
    model = Team

    def get_context_data(self, **kwargs):
        context = super(TeamDetail, self).get_context_data(**kwargs)
        context['poll_list'] = Poll.objects.filter(team=self.kwargs['pk'])  
        context['admin'] = isUserAdmin(self)
        teamid = self.kwargs['pk']
        if not owner(self, teamid):
            raise Http404

        return context



class TeamCreate(CreateView):
    model = Team

    def form_valid(self, form):
        TeamForm = form.save(commit=False)
        self.object = form.save()

        AddUser = TeamMate.objects.create(team=self.object, user=self.request.user, admin=True)
        AddUser.save()

        return super(TeamCreate, self).form_valid(form)

    def get_success_url(self, **kwargs):
        return reverse('teams:TeamDetail', kwargs={'pk': self.object.id})


class InviteUser(CreateView):
    model = Invite
    form_class = InviteUserForm
    success_url = '/'

    def form_valid(self, form):
        TeamForm = form.save(commit=False)
        TeamForm.invite_from = self.request.user


        if owner(self, form.cleaned_data["team"].id):
            self.object = form.save()
        else:
            print "not owner"
            form.clean()
            
        return super(InviteUser, self).form_valid(form)

class InviteResponse(FormView):
    template_name = 'teams/teammate_form.html'
    form_class = InviteResponseForm
    success_url = '/'
    def form_valid(self, form):
        # do the thing
        inviteid = form.cleaned_data["invite_id"]

        inviteobject = Invite.objects.get(id=inviteid)

        # Is this user in the group as well?
        
        if inviteobject.invite_to == self.request.user:
            inviteobject.closed = True
            inviteobject.save()
            if form.cleaned_data["accept"] == "Accept":
                try:
                    TeamMate.objects.create(team=inviteobject.team, user=inviteobject.invite_to, admin=False)
                except:
                    print "failed"


        return super(InviteResponse, self).form_valid(form)

pluginservice/views.py
from django.views.generic import TemplateView, DetailView
from pluginservice.apps.accounts.models import EmailNotification
from pluginservice.apps.teams.models import Invite, TeamMate
from pluginservice.apps.polls.models import Poll


class Homepage(TemplateView):
    template_name = 'site/homepage.html'

    def get_context_data(self, **kwargs):
        context = super(Homepage, self).get_context_data(**kwargs)
        if self.request.user.is_authenticated():
            Listofteams = []

            TeamMateList = TeamMate.objects.filter(user=self.request.user)

            for mate in TeamMateList:
                Listofteams.append(mate.team)

            context ['polls'] = Poll.objects.filter(team__in=Listofteams)

            context['teams'] = TeamMate.objects.filter(user=self.request.user)

            context['invites'] = Invite.objects.filter(invite_to=self.request.user, closed=False)
        return context


class TempProfile(TemplateView):
    template_name = 'site/profile.html'

    def get_context_data(self, **kwargs):
        context = super(TempProfile, self).get_context_data(**kwargs)
        context['EmailNotification'] = EmailNotification.objects.all()
        return context


class Widgets(TemplateView):
    template_name = 'site/widgets.html'


# Not important right now
class PollJS(DetailView):
    model = Poll
    template_name = 'site/js.html'

pluginservice/templates/site/homepage.html
{% extends "base.html" %}
{% block content %}
	{% if user.is_authenticated  %}
        <div id="invitesModal" class="reveal-modal" data-reveal aria-labelledby="modalTitle" aria-hidden="true" role="dialog">
          <h2 id="modalTitle">Your Invites.</h2><hr>
            <ul id="invites"></ul>
          <a class="close-reveal-modal" aria-label="Close">&#215;</a>
        </div>
		 <div id="createpollModal" class="reveal-modal" data-reveal aria-labelledby="modalTitle" aria-hidden="true" role="dialog">
          <h2 id="modalTitle">{{ user.username|title  }}, start out fresh.</h2><hr>
           
		   <div class="large-6 columns">
				<h4><i class="fa fa-user"></i> Create a solo function</h4>
				<p>By creating solo functions you'll be able to use everything Semety has to offer. You can choose this option
			  at anytime, and it won't effect anything related to your teams.
				</p><br/><br/><br/>
			<center><a href="/widgets/polls/create/" class="createapollhref"><i class="fa fa-bar-chart"></i> Create a Poll</a></center>
			<br/><br/>
		   </div>
		   <div class="large-6 columns">
				<h4><i class="fa fa-users"></i> Start out with a team</h4>
				<p>If you choose to start out with a team, you won't miss any of our features either. You will in fact be
		      able to set up your own team with moderators and members, or you can just join a desired team later on.<br/>
				</p><br/><br/>
			<center><a href="/team/create/" class="createapollhref"><i class="fa fa-users"></i> Create a Team</a></center>
			<br/><br/>
		   </div>
		   <hr/>
          <a class="close-reveal-modal" aria-label="Close">&#215;</a>
        </div>
		<br>
		{% if not user.userprofile.tutorial_completed %}
		<div class="row">
		<div class="large-12 columns">
			<div class="panel learnmore"><br/>
					<div class="left"><h2><strong>Start now for free</strong>, create your functions with Semety!</h2></div>
					<div class="right">
						<a href="/create/" data-reveal-id="createpollModal" class="right secondary button small learnmoreButton">START OUT →</a>
					</div>
			</div>
			</div>
		</div>
		{% endif %}	
	<div class="row">
	<div class="large-12 columns">
	<div class="whitebackground left100 title">
	
		
				<h4>Welcome<span class="teamname"> {{ user.username|title  }}</span>, this is your Dashboard!</h4>
				<div class="invitesection disabled"><i class="fa fa-envelope"></i> TEAM INVITES <span>(0)</span></div>
		</div>
		</div>
		<div class="large-12 columns">
		<div class="whitebackground profilemain nobb">
		<h3 class="left joinedteams">
		
			<a href="#"><span class="selected"><i class="fa fa-bookmark-o"></i> Show All</span></a> 
			<a href="#"><span> <i class="fa fa-user"></i> Solo Creations</span></a> 
			<a href="#"><span> <i class="fa fa-users"></i>  Team Creations</span></a></h3>
			
		<div class="teamsearch">
			<input type="text" class="searchfunctions" placeholder="&#128269; Search for a Poll...">
		</div>
		</div>
			<ul class="yourteams">
 				{% for poll in polls %}
					<li>
						<div class="large-8 columns">
							<span class="left">
								<a href="/widgets/polls/{{ poll.id }}">
									<i class="fa fa-users"></i>
									{{ poll.title }} - <small><i>{{ poll.question }}</i></small>
								</a>
							</span>
						</div>
						<div class="large-4 columns">
							<span class="right">
								<a href="#" class="red"><i class="fa fa-bookmark-o"></i></a>
								<a href="/team/{{ poll.team.id }}" class="hg"><i class="fa fa-cog"></i></a>
								<a href="#" class="view hg"><i class="fa fa-bar-chart" style="margin-right:10px;"></i> View Analytics</a>
							</span>
						</div>
					</li>
				{% endfor %}
			</ul>


			<div class="whitebackground left100">
				<div class="left">
					<h4>Your Teams</h4> 
					</div>
				<div class="right">
					<a href="/team/create/" class="buttonSelected2 button small borderradius">View all Teams</a>
				</div>
			</div>

			<ul class="yourteams">
 				{% for team in teams %}
					<li>
						<div class="large-8 columns">
							<span class="left">
								<a href="/widgets/polls/{{ poll.id }}">
									<i class="fa fa-users"></i>
									{{ team.team.name }}
								</a>
							</span>
						</div>
						<div class="large-4 columns">
							<span class="right">
								<a href="#" class="red"><i class="fa fa-bookmark-o"></i></a>
								<a href="/team/{{ poll.team.id }}" class="hg"><i class="fa fa-cog"></i></a>
								{% if team.admin %}
								<a href="#" class="view hg"><i class="fa fa-cogs" style="margin-right:10px;"></i> Manage Team</a>
								{% endif %}
							</span>
						</div>
					</li>
				{% endfor %}
			</ul>


			</div>
		</div>
	</div>
</div>


	{% else %}
	<div id="loginmodal" class="reveal-modal small" data-reveal aria-labelledby="modalTitle" aria-hidden="true" role="dialog">
		<h2>Login</h2>
		<hr>
		<form action="/login/" method="post">
			{% csrf_token %}
			<p><label for="id_username">Username:</label> <input id="id_username" maxlength="254" name="username" type="text"></p>
			<p><label for="id_password">Password:</label> <input id="id_password" name="password" type="password"></p>
			<input type="submit" value="Login" class="small button" / >
		</form>
	  	<a class="close-reveal-modal" aria-label="Close">&#215;</a>
	</div>
	<div id="registermodal" class="reveal-modal small" data-reveal aria-labelledby="modalTitle" aria-hidden="true" role="dialog">
		<h2>Register</h2>
		<hr>
		<form action="/register/" method="post">
            <p><label for="id_username">Username:</label> <input id="id_username" maxlength="30" name="username" type="text">
            <span class="helptext">Required. 30 characters or fewer. Letters, digits and @/./+/-/_ only.</span></p>
			<p><label for="id_email">Email:</label> <input id="id_email" name="email" type="email"></p>
			<p><label for="id_first_name">First name:</label> <input id="id_first_name" maxlength="30" name="first_name" type="text"></p>
			<p><label for="id_last_name">Last name:</label> <input id="id_last_name" maxlength="30" name="last_name" type="text"></p>
			<p><label for="id_password1">Password:</label> <input id="id_password1" name="password1" type="password"></p>
			<p><label for="id_password2">Password confirmation:</label> <input id="id_password2" name="password2" type="password"> <span class="helptext">Enter the same password as above, for verification.</span></p>
             <input type="submit" value="Register" class="small button">
			{% csrf_token %}
		</form>
	  	<a class="close-reveal-modal" aria-label="Close">&#215;</a>
	</div>
	<div class="row">
		<div class="large-12 columns">
			<div class="header clearfix">
				<div class="large-4 small-12 columns">
					<a href="/"><img class="logo2" src="/static/img/logo.png"></a>
				</div>
				
				<ul class="right">
					<li><a href="/register/"> <!-- data-reveal-id="registermodal" --><i class="fa fa-user"></i> Register</a></li>
					<li><a href="/login/"> <!-- data-reveal-id="loginmodal" --><i class="fa fa-sign-in"></i> Log in</a></li>
				</ul>
			</div>
		</div>
	</div>
	<div class="landingblue">
		<div class="row">
			<div class="landingpic">
				<center>
				<br/><br/>
					<a href="#"><img class="youtubebtn" src="/static/img/icons/playbtn.png"/></a>
					<h2 class="lead">Monetize online revenue better, earn more!</h2>
					<h3 class="lead">Bring your web visitors functions instead of just text and pictures on your website.</h3><br/>

					<a href="/register/" class="secondary button small buttonSelected3 big"> Start right now, it's free →</a>
				</center>
			</div>
		</div>
	</div>
	<div class="landinggreen">
		<div class="row">
			<div class="large-4 columns">
			<h5><strong>Semety brings functionality with analytics.</strong></h5><br/>
			<h6>This poll function brings storytelling to another level, it's independent and will analyze answers and patterns.</h6>
			</div>
			<div class="large-8 columns">
			<div class="poll">
					<div class="pollgrid clearfix">
						<div class="left">
							<h2>Will you use Semety for your advantage?</h2>
						</div>
					<div class="right">
							
					</div>
					<div class="clearfix"></div>

					<a href="#">
						<div class="polloption">
							<h3>Yes, this sounds very interesting!</h3>
						</div>
					</a>
					<a href="#">
						<div class="polloption">
							<h3>No, I don't have any use for this yet.</h3>
						</div>
					</a>
					<a href="#">
						<div class="polloption">
								<h3>I don't have any opinion, I just came to check it out.</h3>
						</div>
					</a>

					<div class="pollfooter">
						<a href=""><small>Powered by Semety 2015</small></a>
					</div>
				</div>
			</div>
			</div>
			</div>
			</div>
		</div>
	</div>
	<div class="landingpurple">
		<div class="row">
			<div class="large-7 columns"><br/><br/>
				<img src="/static/img/intro-pic1.png"/>
			</div>
			<div class="large-5 columns"><br/>
				<h5><strong>So how do I start?</strong></h5>
				<h6>Sign up and <strong>create for free</strong> through the Semety platform, then copy & paste your function on to a website. Wait and look at the analytics to see how you can greatly improve your website or business with <strong>more online revenue</strong>.</h6>		
		</div>
		</div>
	</div>
	<div class="landingdark">
		<div class="row">
			<div class="large-6 columns">
				<h5><strong>New Technology for Both Individuals and Businesses.</strong></h5>
				<h6>We offer <strong>smart analytics</strong> that gives feedback on essential activity. The analytics will stream in after a function is added, so sit back and enjoy the information flow.</h6>						
			</div>
			<div class="large-6 columns"><br/><br/>
					<img src="/static/img/intro-pic2.png"/>
			</div>
		</div>
	</div>
	<div class="landingorange">
		<div class="row">
			<div class="large-7 columns"><br/>
				<img src="/static/img/intro-pic3.png"/>
			</div>
			<div class="large-5 columns"><br/>
				<h5><strong>Be in the team you deserve, literally.</strong></h5>
				<h6>Semety offers team creations and invites, <strong>where you can work efficiently</strong> with your team to create and analyze the best functions widespread.</h6>
			</div>
	</div><br/>
	<div class="landingwhite">
		<div class="row">
			<center>
				<h5><em>Some of the famous places you can use us</em></h5><br/><br/>
				<ul class="small-block-grid-3 medium-block-grid-6 large-block-grid-6 frontpagelogos">
					<li><img src="/static/img/home/frontpage/1.png"></li>
					<li><img src="/static/img/home/frontpage/2.png"></li>
					<li><img src="/static/img/home/frontpage/3.png"></li>
					<li><img src="/static/img/home/frontpage/4.jpg"></li>
					<li><img src="/static/img/home/frontpage/5.png"></li>
					<li><img src="/static/img/home/frontpage/6.png"></li>
					<li><img src="/static/img/home/frontpage/7.png"></li>
					<li><img src="/static/img/home/frontpage/8.png"></li>
					<li><img src="/static/img/home/frontpage/9.png"></li>
				</ul><br/><hr/><br/>
				<h6>Our <strong>13,878 users</strong> have already generated <strong>460,112 functions</strong>, are you ready?</h6><br/><br/>
				<h6>Ohoy' there!</h6>

				<a href="/tutorial/" class="secondary button small buttonSelected2 big">Are you still not convinced about Semety?</a>
			</center>
		</div>

	{% endif %}
{% endblock%}