pluginservice/apps/api/urls.py
from django.conf.urls import patterns, url
from .views import API, Styles, InviteViewSet, UserViewSet, UserDetailViewSet


urlpatterns = patterns(
    '',
    url(r'^api/polls/(?P<pk>\d+).js$', API.as_view(), name='Api'),
    url(r'^api/polls/styles.css$', Styles.as_view(), name='Styles'),
    url('^api/users/(?P<team>.+)/$', UserViewSet.as_view()),
    url('^api/invites/$', InviteViewSet.as_view()),
    url('^api/user/(?P<pk>.+)/$', UserDetailViewSet.as_view()),
)

pluginservice/apps/polls/urls.py
from django.conf.urls import patterns, url
from .views import PollCreate, PollCreateSuccess, PollDetail, PollHome


urlpatterns = patterns(
    '',
    #url(r'^$', PollHome.as_view(), name='PollHome'),
    url(r'^create/$', PollCreate.as_view(), name='PollCreate'),
    url(r'^(?P<pk>\d+)/$', PollDetail.as_view(), name='PollDetail'),
    url(r'^(?P<pk>\d+)/help/$', PollCreateSuccess.as_view(), name='success'),
)

pluginservice/apps/teams/urls.py
from django.conf.urls import patterns, url
from .views import TeamList, TeamDetail,TeamCreate, InviteResponse, InviteUser

urlpatterns = patterns(
    '',
    url(r'^$', TeamList.as_view(), name='home'),
    url(r'^(?P<pk>\d+)/$', TeamDetail.as_view(), name='TeamDetail'),
    url(r'^create/$', TeamCreate.as_view(), name='Create'),
    url(r'^invitereponse/$', InviteResponse.as_view(), name='Create'),
    url(r'^invite/$', InviteUser.as_view(), name='Create'),
    
    
    
)

pluginservice/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from django.conf import settings
from .views import Homepage, TempProfile, Widgets, PollJS
from pluginservice.apps.navigation.views import PageDetail
from apps.api.views import InviteViewSet, UserViewSet, NotificationViewSet, PollVoteViewSet, TeamViewSet
from rest_framework import routers

router = routers.DefaultRouter()
router.register(r'users', UserViewSet, base_name='users')
router.register(r'invites', InviteViewSet, base_name='invites')
router.register(r'notifications', NotificationViewSet, base_name='notifications')
router.register(r'votes', PollVoteViewSet, base_name='votes')
router.register(r'teams', TeamViewSet, base_name='teams')

admin.autodiscover()


urlpatterns = patterns(
    '',
    url(r'^$', Homepage.as_view(), name='homepage'),
    url(r'^profile/$', TempProfile.as_view(), name='TempProfile'),
    #url(r'^widgets/$', Widgets.as_view(), name='Widgets'),
    url(r'^widgets/polls/', include('pluginservice.apps.polls.urls', namespace="polls")),
    url(r'^team/', include('pluginservice.apps.teams.urls', namespace="teams")),
    url(r'^', include('pluginservice.apps.accounts.urls', namespace="accounts")),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^login/$', 'django.contrib.auth.views.login', name='login'),
    url(r'^logout/$', 'django.contrib.auth.views.logout', {'next_page': '/'}, name='logout'),
    url(r'^api/', include(router.urls)),
    url(r'^api/widgets/polls/(?P<pk>\d+).js$', PollJS.as_view(), name='PollList'),
    url(r"^(?P<page_slug>[^/]+)/$", PageDetail.as_view(), name="page_slugs"),
)

if settings.DEBUG:
    # static files (images, css, javascript, etc.)
    urlpatterns += patterns('',
        (r'^media/(?P<path>.*)$', 'django.views.static.serve', {
        'document_root': settings.MEDIA_ROOT}))

pluginservice/apps/teams/models.py
from django.contrib.auth.models import User
from django.db import models


class Team(models.Model):

    name = models.CharField(
        max_length=200
    )

    def __unicode__(self):
        return self.name


class TeamMate(models.Model):

    team = models.ForeignKey(
        Team
    )

    user = models.ForeignKey(
        User
        )

    admin = models.BooleanField(
        default=False,
    )

    class Meta:
        unique_together = ["team", "user"]


class Invite(models.Model):
    
    invite_from = models.ForeignKey(
        User
        )

    invite_to = models.ForeignKey(
        User,
        related_name='invite_to'
        )

    team = models.ForeignKey(
        Team,
        null=True
        )

    message = models.TextField(
        null=True,
        blank=True,
        )

    closed = models.BooleanField(
        default=False
        )

pluginservice/apps/accounts/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm

class UserCreateForm(UserCreationForm):
    email = forms.EmailField(required=True)

    class Meta:
        model = User
        fields = ("username", "email", "first_name", "last_name", "password1", "password2")

    def save(self, commit=True):
        user = super(UserCreateForm, self).save(commit=False)
        user.email = self.cleaned_data["email"]
        user.first_name = self.cleaned_data["first_name"]
        user.last_name = self.cleaned_data["last_name"]
        if commit:
            user.save()
        return user

pluginservice/apps/polls/forms.py
from django import forms
from .models import Poll


class CreateForm(forms.ModelForm):
    choice1 = forms.CharField(required=False)
    choice2 = forms.CharField(required=False)
    choice3 = forms.CharField(required=False)

    class Meta:
        model = Poll
        exclude = ['created_by', 'deleted']

pluginservice/apps/accounts/views.py
from django.views.generic import FormView, UpdateView
from django.forms.models import inlineformset_factory
from django.core.urlresolvers import reverse
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm, PasswordChangeForm
from .forms import UserCreateForm
from .models import UserProfile
from django.contrib.auth import authenticate, login

class CreateAccount(FormView):
    template_name = 'accounts/register.html'
    form_class = UserCreateForm
    success_url = '/'

    def form_valid(self, form):
        createform = form.save(commit=False)
        createform.username = form.cleaned_data['username'].lower()
        self.object = form.save()

        user = authenticate(
            username=form.cleaned_data['username'].lower(),
            password=form.cleaned_data['password1']
        )

        if user is not None:
            if user.is_active:
                login(self.request, user)

        return super(CreateAccount, self).form_valid(form)

class ChangePassword(FormView):
    form_class = PasswordChangeForm


class TutorialForm(FormView):
    template_name = 'accounts/register.html'
    success_url = '/'

    def form_valid(self, form):   
        user = UserProfile.get(user=self.request.user)
        user.tutorial_completed = True;
        user.save()


class UserProfileUpdate(FormView):
    model = UserProfile

pluginservice/apps/api/views.py
from django.views.generic import DetailView, TemplateView
from pluginservice.apps.polls.models import Poll, Vote, PollAnswer
from pluginservice.apps.teams.models import Invite, TeamMate, Team
from pluginservice.apps.notifications.models import Notification
from rest_framework import viewsets
#from django.http import HttpRequest
from .serializers import InviteSerializer, UserSerializer, NotificationSerializer, PollVoteSerializer, TeamModelSerializer
from rest_framework import serializers
from django.contrib.auth.models import User
from rest_framework import generics, filters
from datetime import datetime

def TeamPlayers(teamID):
    tlist = []

    players = TeamMate.objects.filter(team=teamID)
    invites = Invite.objects.filter(team=teamID, closed=False)

    for player in invites:
        tlist.append(player.invite_to.id)

    for player in players:
        tlist.append(player.user.id)

    return tlist


def YourTeams(userID):
    tlist = []

    results = TeamMate.objects.filter(user=userID)

    for result in results:
        tlist.append(Team.objects.get(id=result.team.id))

    return tlist


class UserViewSet(viewsets.ReadOnlyModelViewSet):
    """
    View the detail of a user and filter by team the avalible users that can be invited
    """
    def get_queryset(self):
        inviteable = self.request.query_params.get('inviteable', None)
        team = self.request.query_params.get('team', None)
        queryset = User.objects.all();

        if inviteable:
            tlist = TeamPlayers(inviteable)
            return User.objects.exclude(pk__in=tlist)

        if team:
            tlist = TeamPlayers(team)
            return User.objects.filter(pk__in=tlist)


        return queryset

    serializer_class = UserSerializer
    serializer = UserSerializer
    filter_backends = (filters.SearchFilter,)
    search_fields = ('username', 'email')


class InviteViewSet(viewsets.ReadOnlyModelViewSet):
    """
    Returns a list of the current invites you have.
    """
    serializer_class = InviteSerializer

    def get_queryset(self):

        user = self.request.user
        print user
        return Invite.objects.filter(invite_to=user, closed=False)


class NotificationViewSet(viewsets.ReadOnlyModelViewSet):
    """
    Returns a list of the current Notifications you have.
    """
    serializer_class = NotificationSerializer

    def get_queryset(self):
        user = self.request.user
        result = Notification.objects.filter(user=user, read=False)
        print result
        return result


class PollVoteViewSet(viewsets.ModelViewSet):
    """
    Allows someone to vote on a poll
    """

    serializer_class = PollVoteSerializer
    def get_queryset(self):

        """
        step 1 get all the teams the user is in
        step 2 filter by the polls the users is involved in
        step 3 get all the votes ass
        """

        userteammates = TeamMate.objects.filter(user=self.request.user)
        teams = []
        for teammateobject in userteammates:
            teams.append(teammateobject.team)


        #return Vote.objects.filter(team__in=teams)
        return Vote.objects.filter(choice__poll=1)


class TeamViewSet(viewsets.ReadOnlyModelViewSet):
    """
    Returns a list of the current Teams you have.
    """
    serializer_class = TeamModelSerializer

    def get_queryset(self):
        user = self.request.user

        return YourTeams(user)

pluginservice/apps/navigation/views.py
from django.views.generic import DetailView
from .models import Page

class PageDetail(DetailView):
    model = Page
    template_name = 'site/navigation-page.html'
    slug_field = 'slug'
    slug_url_kwarg = 'page_slug'

pluginservice/apps/notifications/views.py
from django.views.generic import FormView
from django.forms.models import inlineformset_factory
from django.core.urlresolvers import reverse
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm, PasswordChangeForm
from .forms import UserCreateForm
from django.contrib.auth import authenticate, login

def CreateNotifcation(to_user, text ):
    return text

pluginservice/apps/polls/views.py
from django.views.generic import ListView, CreateView, DetailView, TemplateView
from .models import Poll, PollAnswer
from django.forms.models import inlineformset_factory
from django.core.urlresolvers import reverse
from pluginservice.settings.production import CURRENT_SITE_URL
from .forms import CreateForm
from pluginservice.apps.teams.models import Team, TeamMate
from django.http import Http404

class PollHome(TemplateView):
    template_name = 'polls/polls_home.html'


def isUserAdmin(self):

    try:
     user = TeamMate.objects.get(team=self.kwargs['pk'], user=self.request.user)

     if user.admin:
        return True
     else:
        return False
    except:
        return False

class PollDetail(DetailView):
    model = Poll

    def get_context_data(self, **kwargs):
        context = super(PollDetail, self).get_context_data(**kwargs)
        poll = Poll.objects.get(id=self.kwargs['pk'])
        context['checker'] = owner(self, poll.team.id)
        return context

def owner(self, teamid):
        people = TeamMate.objects.filter(team=teamid)
        exists = False

        if people:
            for person in people:
                if person.user.id == self.request.user.id:
                    return True
                else:
                    exists = False

            if not exists:
                return False
        else:
            return False    

class PollCreate(CreateView):
    model = Poll
    form_class = CreateForm
    #success_url = '/polls/create/success/'

    def form_valid(self, form):
        PollForm = form.save(commit=False)
        PollForm.created_by = self.request.user
        self.object = form.save()

        choice1 = form.cleaned_data['choice1']
        choice2 = form.cleaned_data['choice2']
        choice3 = form.cleaned_data['choice3']


        if choice1 != "":
            CreateAnswers = PollAnswer.objects.create(poll=self.object, answer=choice1)
            CreateAnswers.save()

        if choice2 != "":
            CreateAnswers = PollAnswer.objects.create(poll=self.object, answer=choice2)
            CreateAnswers.save()

        if choice3 != "":
            CreateAnswers = PollAnswer.objects.create(poll=self.object, answer=choice3)
            CreateAnswers.save()


        return super(PollCreate, self).form_valid(form)

    def get_success_url(self, **kwargs):
        return reverse('polls:success', kwargs={'pk': self.object.id})


class PollCreateSuccess(DetailView):
    model = Poll
    template_name = 'polls/poll_success.html'

    def get_context_data(self, **kwargs):
        context = super(PollCreateSuccess, self).get_context_data(**kwargs)
        context['current_site_url'] = CURRENT_SITE_URL
        return context

pluginservice/apps/teams/views.py
from django.views.generic import TemplateView, CreateView, ListView, FormView, DetailView
from django.contrib.auth.models import User
from .models import Team, Invite, TeamMate
from django.core.urlresolvers import reverse
from .forms import InviteResponseForm, InviteUserForm
from pluginservice.apps.polls.views import owner, isUserAdmin
from pluginservice.apps.polls.models import Poll

class TeamList(ListView):
    model = Team

    def get_queryset(self):
        teamlist = []

        for team in Team.objects.all():
            if owner(self, team.id):
                teamlist.append(team.id)

        queryset = Team.objects.filter(id__in=teamlist)
        return queryset



class TeamDetail(DetailView):
    model = Team

    def get_context_data(self, **kwargs):
        context = super(TeamDetail, self).get_context_data(**kwargs)
        context['poll_list'] = Poll.objects.filter(team=self.kwargs['pk'])  
        context['admin'] = isUserAdmin(self)
        teamid = self.kwargs['pk']
        if not owner(self, teamid):
            raise Http404

        return context



class TeamCreate(CreateView):
    model = Team

    def form_valid(self, form):
        TeamForm = form.save(commit=False)
        self.object = form.save()

        AddUser = TeamMate.objects.create(team=self.object, user=self.request.user, admin=True)
        AddUser.save()

        return super(TeamCreate, self).form_valid(form)

    def get_success_url(self, **kwargs):
        return reverse('teams:TeamDetail', kwargs={'pk': self.object.id})


class InviteUser(CreateView):
    model = Invite
    form_class = InviteUserForm
    success_url = '/'

    def form_valid(self, form):
        TeamForm = form.save(commit=False)
        TeamForm.invite_from = self.request.user


        if owner(self, form.cleaned_data["team"].id):
            self.object = form.save()
        else:
            print "not owner"
            form.clean()
            
        return super(InviteUser, self).form_valid(form)

class InviteResponse(FormView):
    template_name = 'teams/teammate_form.html'
    form_class = InviteResponseForm
    success_url = '/'
    def form_valid(self, form):
        # do the thing
        inviteid = form.cleaned_data["invite_id"]

        inviteobject = Invite.objects.get(id=inviteid)

        # Is this user in the group as well?
        
        if inviteobject.invite_to == self.request.user:
            inviteobject.closed = True
            inviteobject.save()
            if form.cleaned_data["accept"] == "Accept":
                try:
                    TeamMate.objects.create(team=inviteobject.team, user=inviteobject.invite_to, admin=False)
                except:
                    print "failed"


        return super(InviteResponse, self).form_valid(form)

pluginservice/views.py
from django.views.generic import TemplateView, DetailView
from pluginservice.apps.accounts.models import EmailNotification
from pluginservice.apps.teams.models import Invite, TeamMate
from pluginservice.apps.polls.models import Poll


class Homepage(TemplateView):
    template_name = 'site/homepage.html'

    def get_context_data(self, **kwargs):
        context = super(Homepage, self).get_context_data(**kwargs)
        if self.request.user.is_authenticated():
            Listofteams = []

            TeamMateList = TeamMate.objects.filter(user=self.request.user)

            for mate in TeamMateList:
                Listofteams.append(mate.team)

            context ['polls'] = Poll.objects.filter(team__in=Listofteams)

            context['teams'] = TeamMate.objects.filter(user=self.request.user)

            context['invites'] = Invite.objects.filter(invite_to=self.request.user, closed=False)
        return context


class TempProfile(TemplateView):
    template_name = 'site/profile.html'

    def get_context_data(self, **kwargs):
        context = super(TempProfile, self).get_context_data(**kwargs)
        context['EmailNotification'] = EmailNotification.objects.all()
        return context


class Widgets(TemplateView):
    template_name = 'site/widgets.html'


# Not important right now
class PollJS(DetailView):
    model = Poll
    template_name = 'site/js.html'

pluginservice/templates/teams/invite_form.html
{% extends 'base.html' %}
{% block content %}
<form method="post">
{% csrf_token %}
{{ form.as_p }}
<input type="submit">
</form>
{% endblock %}

pluginservice/templates/teams/team_detail.html
{% extends "base.html" %}

{% block content %}
	<div id="teammateadd" class="reveal-modal meduim" data-reveal aria-labelledby="modalTitle" aria-hidden="true" role="dialog">
		<h2>Add Teammate</h2>
		<hr>

		<input type="text" placeholder="Search" id="search"  onkeyup="return Search(event, false);">
			
			<h4>Results:</h4>
			<ul class="poll-list team" id="search-results">

			{% for person in team.teammate.set.all %}
			<li><img src="/static/img/example.png">{{ user.first_name }} {{ user.last_name }}</li>
			<li><img src="/static/img/default.png">Peter Pan</li>
			{% endfor %}
			</ul>

	  	<a class="close-reveal-modal" aria-label="Close">&#215;</a>
	</div>
	<br>
			<div class="row">

			<div class="whitebackground left100 simple-single">
						<div class="large-12 columns">
				<div class="left">
				<h3><small>Team</small> {{ team.name }}</h3>
				</div>
				<div class="right">
				  <a href="/widgets/polls/create/" class="buttonSelected2 button small">Create Poll</a>
				</div>
			</div></div>
	<div class="white left100 simple">
			<div class="large-4 columns">
			<div class="whitebackground left100">
			<h4>Team Involved</h4>
			<ul class="poll-list team" id="team">
			{% for person in team.teammate_set.all %}
			<li><img src="/media/{{ person.user.userprofile.profile_picture }}"><h4>{{ person.user.first_name }} {{ person.user.last_name }}</h4></li>
			{% endfor %}
			</ul>
			{% if admin %}
			<a href="#" data-reveal-id="teammateadd" class="add-button"><i class="fa fa-plus-circle"></i>Add Teammate</a>
			{% endif %}
			</div>
			</div>
			<div class="large-8 columns">
			<div class="whitebackground left100">

			<h4>Poll Activity</h4>
			<ul class="poll-list">
			{% for poll in poll_list %}
				<li>
					<a href="/widgets/polls/{{ poll.id }}" class="right poll-edit"><i class="fa fa-cog"></i> Edit</a> 
					<h5>{{ poll.title }}</h5>
					<small>by {{ poll.created_by.first_name }} {{ poll.created_by.last_name }}</small>
				</li>
			{% endfor %}
			</ul>

			</div>

			</div>			
{% endblock %}

{% block js %}
	

	<script>
	var Team = {{ team.id }}
	
	function Invite(userid) {


	    submit = "/team/invite/";
	    form = "invite_to=" + userid + "&team={{ team.id }}&csrfmiddlewaretoken={{ csrf_token }}"
	    $.post(submit, form).fail(function () {
	        setTimeout(failed, 500);
	    }).done(function () {
	        setTimeout(complete, 500);
	        $('#user' + userid).html("<p>User has been invited</p>")
	    });

	}

	function failed() {}
	function complete() {

	}

	</script>
{% endblock js %}

pluginservice/templates/teams/team_form.html
{% extends 'base.html' %}

{% block content %}

<br>

<div class="row">
	<div class="large-12 columns">
		<div class="whitebackground left100 simple-single">
			<h3>Create your own Team.</h3>
		</div>
		<div class="whitebackground left100 simple-single">
			<p class="subheading">Let us guide you through creating a team for your company, team or group!</p>
		</div>
		<div class="whitebackground left100 simple-single"><br/>
			<div class="large-12 columns">
				<form method="post">
					{{form.as_p }}
					{% csrf_token %} 
					<input type="submit" style="width:100%;background: rgb(51, 96, 163);padding: 20px;font-size:1.4rem;"class="button small" value="Create Team">
					</form><br/>
			</div>
		</div>
	</div>
</div>

{% endblock %}

pluginservice/templates/teams/team_list.html
{% extends 'base.html' %}

{% block content %}
	<br>
	<div class="row">
	<div class="large-12 columns">
	<div class="whitebackground left100 simple">
        <div class="left">
            <h3>TEAMS</h3>
        </div>
        <div class="right">
            <a href="/team/create/" class="buttonSelected2 button small">Create Team</a>
        </div>
	</div>
	<div class="whitebackground profilemain nobb">
			<p>Create, delete and manage your teams.</p>
	</div>
	</div>

	<div class="large-12 columns">
		<ul class="team-list">
			{% for team in team_list %}
			  <li class="team-header">
		        <div class="left">
		            <h4>{{ team.name }}</h4>
		        </div>
		        <div class="right team-buttons">
				    <a href="invite/"><i class="fa fa-plus"></i> Invite</a>
		            <a href="/team/{{ team.id }}"><i class="fa fa-eye"></i> Team Page</a> 
					<a href="#"><i class="fa fa-pencil"></i> Edit</a> 
		        </div>

	          </li>
	          <li class="team-divider">

				<ul class="team-page">
					{% for person in team.teammate_set.all %}
					<li>
					<img src="/media/{{ person.user.userprofile.profile_picture }}">
					<p>	{{ person.user.first_name }} {{ person.user.last_name }} {% if person.admin %}<small>Admin</small>{% endif %}</p>

					</li>
					{% endfor %}
				</ul>
			  </li>
			{% endfor %}

			
		</ul>
	</div>

	</div>
{% endblock %}

pluginservice/templates/teams/teammate_form.html
{{ form.as_p }}